services:
  react-app:
    image: client-react-vite:latest
    build:
      context: ./react-app
      dockerfile: Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./react-app/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules 
      - type: bind
        source: ./react-app/vite.config.js
        target: /usr/src/app/vite.config.js
    environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost:8080
     - VITE_CF_TURNSTILE_SITE=${CF_TURNSTILE_SITE_DEV}
    networks:
      - app-network
    ports:
      - 5173:5173
  api-server:
    image: api-server:latest
    build:
      context: ./api_server
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - db
    init: true
    volumes:
      - type: bind 
        source: .
        target: /app
    env_file: ".env"
    environment:
      - PYTHONPATH=/app
      - CF_TURNSTILE_SECRET=${CF_TURNSTILE_SECRET_DEV}
      - POSTGRES_HOST=${POSTGRES_HOST_DEV}
      - DOMAIN=http://localhost:5173
    networks:
      - app-network
    ports:
      - 8080:8080
  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=vector"]
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - app-network
    ports:
      - 5432:5432


networks:
  app-network:
    driver: bridge
volumes:
  pgdata:


